### ISSUE TITLE
Preview Image showing wrong image. 

### ISSUE THREAD

**Issue by Leykwan132** [MaeWolff/astro-portfolio-template#10]
![image](https://github.com/MaeWolff/astro-portfolio-template/assets/56620672/b1913979-02e2-4710-9a56-bc497047a449)

Hi Mae, Thank you for the awesome template first off all!

I'd like to know which part should be changed so that the preview image is not the demo site?

**This is the /posts path**

**Comment by MaeWolff** [comment]
Hi @Leykwan132 ! You can change this image from the public folder (https://github.com/MaeWolff/astro-portfolio-template/blob/main/public/opengraph-image.jpg)

edit: Your image is displayed on my side for the posts path :)

**Comment by Leykwan132** [comment]
Does that mean it's working just fine? I was trying this out on Linkedin.

**Comment by MaeWolff** [comment]
> Does that mean it's working just fine? I was trying this out on Linkedin.

Yes it works well! ![image](https://github.com/MaeWolff/astro-portfolio-template/assets/56693082/ce192627-dbb8-447c-b343-a9280566f26b)

**Comment by Leykwan132** [comment]
![image](https://github.com/MaeWolff/astro-portfolio-template/assets/56620672/38633eb3-2e26-4f77-b49f-45b778091874)

for some reason, it's still giving me the demo picture when I'm using the /posts endpoint. Which part should be changed?

**Comment by MaeWolff** [comment]
Hmmm..I tried to investigate, does your image respect the standards? (https://developers.facebook.com/blog/post/2013/04/03/platform-updates--operation-developer-love/)

**Comment by MaeWolff** [comment]
@Leykwan132 good for you? I can close this issue?

**Comment by Leykwan132** [comment]
Yea it's good now. Thanks!
